### ISSUE TITLE
some problems

### ISSUE THREAD

**Issue by mgdgfbhevdyeh** [larrythemodder/plantmegapack-source#12]
Some two-tall plants seem to have some problems
I do not know is a block itself or overlap model
In addition
I found a lot less plants
Can you put those plants back?
You can repair so many BUG and released the official version（final version）?
You can maintain the same as 10paktimbit MOD?

**Comment by mgdgfbhevdyeh** [comment]
English is not very good for me

**Comment by larrythemodder** [comment]
Clone of #8
