### ISSUE TITLE
[suggestion] [request]

### ISSUE THREAD

**Issue by ziadbenaman** [larrythemodder/plantmegapack-source#3]
Hi,  would you please backport the new stuff in 1.9  and 1.8 versions to 1.7.10,  it will be great if you do it because a lot of modpacks are still in this version (some beautiful mods are not updating to 1.8|1.9 or not updating at all like witchery,  carpenter blocks...)  and too many players still using this version.

**Comment by tetsune** [comment]
I don't think most of this is possible, because of the way the newer versions render models and stuff.
That's why 10Pak never made Decoration Mega Pack lower than 1.8

Also Carpenters Blocks is on it's way to being updated.

**Comment by ziadbenaman** [comment]
Ok thank you very much.  Also for player who want the new stuff on 1.7 waiting for the update of their mods,  i fount a mod called Garden stuff,  it adds the pots and the other stuff from pmp 1.8

**Comment by larrythemodder** [comment]
@ziadbenaman Apologies for the wait, I've been on break from modding! It's an interesting idea, but I'd have to check into it a bit further to see if it's possible.
