### ISSUE TITLE
Oredictionaries need to be applied to the harvests of crops, not the crops themselves

### ISSUE THREAD

**Issue by Sunconure11** [larrythemodder/plantmegapack-source#4]
> On a side note, you should probably do something about the oredictionary derpiness this mod has.
> 
> For instance, if I wanted to use a recipe that called for tomatoes for any mod that registered an oredictionary definition for them, I could use whole plants, which is not intended, and impossible for the most part, unless there is some magical way of getting fully grown tomato plants in your inventory without creative mode. I suggest fixing that, and adding some generic oredictionary definitions that encompass most plants as well.
> 
> Look at harvestcraft and how it does oredictionary definitions to fix this issue.

A lot of the crops are not applying their oredictionary definitions to their harvests, and as a result, you get stuff like full tomato plants (you cannot shear crops IIRC) with an oredictionary that should be used for the fruit itself. This needs to be fixed, but I have no clue how to handle this, due to the weird codebase.

@larrythemodder If you can, I suggest looking into this.

**Comment by larrythemodder** [comment]
plantmegapack.item.PMPItemFood.java
`public class PMPItemFood extends ItemFood {
	private PMPFood food;
	
	public PMPItemFood(PMPFood food) {
...
		OreDictionary.registerOre(this.food.oreDictName, this);
	}`

plantmegapack.object.PMPFood.java
`public enum PMPFood {
	foodAcaiberry("foodAcaiberry", PMPFoodType.berr, 1, 0.1F, -1, EnumSet.of(PMPFoodUse.frdr, PMPFoodUse.tead, PMPFoodUse.tree)),`
`	private PMPFood(String oreDictName, PMPFoodType foodType, int foodValue, float saturation, int salveID, EnumSet<PMPFoodUse> foodUses) {
		this.oreDictName = oreDictName;`

Based on the code, it looks like the actual food items are the ones registered to the oredict. Where in the code do you see an issue?

**Comment by Sunconure11** [comment]
In older versions, the fruit would not have definitions. I will check this out later then.

**Comment by Sunconure11** [comment]
https://www.dropbox.com/s/44jvejkxh8y05tg/Screenshot%202016-11-01%2008.28.24.png?dl=0

Bug still exists.

I also found this:

https://www.dropbox.com/s/sng72iy9lolrmib/Screenshot%202016-11-01%2008.28.11.png?dl=0

**Comment by larrythemodder** [comment]
@Sunconure11 Yeah, I'm aware of the tags thing. Personally, I wouldn't mind removing them, but for now I'll try to fix them.

**Comment by larrythemodder** [comment]
Alright, fixed the problem. Crop plants are now "plantX" instead of "cropX" in the Ore Dictionary.
